/// Mapa estático ticker → sector para concentración y fit score.
const tickerSectorMap = <String, String>{
  'AAPL': 'Technology',
  'MSFT': 'Technology',
  'NVDA': 'Technology',
  'GOOGL': 'Technology',
  'GOOG': 'Technology',
  'META': 'Technology',
  'AMD': 'Technology',
  'INTC': 'Technology',
  'CRM': 'Technology',
  'ORCL': 'Technology',
  'AMZN': 'Consumer',
  'TSLA': 'Consumer',
  'NKE': 'Consumer',
  'MCD': 'Consumer',
  'COST': 'Consumer',
  'WMT': 'Consumer',
  'HD': 'Consumer',
  'JPM': 'Financials',
  'BAC': 'Financials',
  'GS': 'Financials',
  'MS': 'Financials',
  'V': 'Financials',
  'MA': 'Financials',
  'XOM': 'Energy',
  'CVX': 'Energy',
  'COP': 'Energy',
  'SLB': 'Energy',
  'JNJ': 'Healthcare',
  'PFE': 'Healthcare',
  'UNH': 'Healthcare',
  'ABBV': 'Healthcare',
  'MRK': 'Healthcare',
  'PG': 'Consumer Staples',
  'KO': 'Consumer Staples',
  'PEP': 'Consumer Staples',
};

String? sectorForTicker(String ticker) =>
    tickerSectorMap[ticker.toUpperCase()];
